### ISSUE TITLE
How to create .gsa or .gsb file

### ISSUE THREAD

**Issue by andreiste** [Esri/ntv2-file-routines#5]
Hello,

I have a .grt file which I can read as plain text and which contains all my grid shift information. I tried to edit a .gsa file with the information contained by my file in order to convert it with the ntv2_file tool provided here into grid shift binary file (.gsb), but I noticed in the end that the tool doesn't read or write my information correctly and for all values including 0 it writes in the .gsb file a default value -431602080.0 
I think it is because of my input .gsa file.. All the information that I modified in the header was read and written correctly by the ntv2_file tool, from .gsa to .gsb but also from .gsb to .gsa. The problem is only with the shifted grid values... Is there a special tool or other solution that I can use to edit or create a .gsa file in order to convert it into .gsb?

Thank you very much in advance for your answer and time,
Andrei Stefan

**Comment by melitakennedy** [comment]
Hi Andrei, 

Are the offset values in arc-seconds? Here's the first few lines from an ascii version of the New Zealand NTv2 file:

NUM_OREC 11
NUM_SREC 11
NUM_FILE  1
GS_TYPE SECONDS 
VERSION NZV1.0  
SYSTEM_FNZGD49  
SYSTEM_TNZGD2000
MAJOR_F  6378388.000
MINOR_F  6356911.946
MAJOR_T  6378137.000
MINOR_T  6356752.314
SUB_NAMENZNAT   
PARENT  NONE    
CREATED 20111999
UPDATED 20111999
S_LAT    -172800.000000
N_LAT    -122400.000000
E_LONG   -648000.000000
W_LONG   -597600.000000
LAT_INC      360.000000
LONG_INC     360.000000
GS_COUNT 19881
  5.875380 -1.376003  0.090471  0.135207
  5.874535 -1.368036  0.089857  0.134289
  5.873609 -1.360069  0.089238  0.133364
  5.872601 -1.352099  0.088613  0.132431

**Comment by andreiste** [comment]
Thank you very much for your response! Yes, this might be the problem.  I didn't have any information regarding the grid shift units of my file and I thought to try the ntv2_file tool with the grid shift values as they are to see what results do I get. Didn't expect to have all the values changed to -431602080.0 I will try to transform them into arc-seconds.
